packages:
  - "packages/*"
  - "tauri-cblite-example"
  - "web-cblite-example"
  - "email-worker"
  - "github-worker"
  - "gitlab-worker"
  - "jira-worker"
  - "slack-worker"
  - "outlook-worker"
  - "calendly-worker"
  - "telegram-worker"
  - "whatsapp-worker"
  - "signal-worker"
  - "imap-worker"
